### ISSUE TITLE
Should a `get` action print `O.K.`?

### ISSUE THREAD

**Issue by drewish** [MikeTaylor/scottkit#34]
I wanted to override the first `get foo` of the game to give a bit more info so I'd done something like:
```
action get form
  get blank-form
  print "I pick up the blank form. Looks like I'll need to *complete* it."
```
But that prints:
```
Tell me what to do ? get form
O.K.
I pick up the blank form. Looks like I'll need to *complete* it.
```
And the `O.K.` in there feels a bit out of place. Switching to a `superget` avoided printing the message but I'm wondering if that's something that was deliberate to match the output of scottfree.

**Comment by MikeTaylor** [comment]
Good catch. Re-reading the ScottFree source, it's apparent that it does not emit an "OK" there (and therefore, I assume, neither did the old Scott Adams games drivers). I will modify ScottKit accordingly.

**Comment by MikeTaylor** [comment]
I can confirm from the _Adventureland_ play-through that the automatic "O.K." on a GET action is indeed incorrect: the transcript includes things like:
```
Tell me what to do ? get mud
O.K.
OK
BOY that really hit the spot!
```
