### ISSUE TITLE
No .gemspec file

### ISSUE THREAD

**Issue by drewish** [MikeTaylor/scottkit#9]
I'd been using the code from the gem but now that I'm looking at making some changes that could become a PR I was going to just source the code from git but it doesn't seem to be a `.gemspec` file. Perhaps it didn't get committed to git?

**Comment by MikeTaylor** [comment]
I'm using jeweler to make gems. It was a long time ago that I set this up (2010!) but IIRC it generates the gemspec on the fly, as it's needed, from data in the Rakefile. So if you want your PR to include changes to the gemspec, make those changes to the settings in the Rakefile and all should be well.

If that answer satisfies you, feel free to close this issue; if not, let me know what you think should happen.

**Comment by drewish** [comment]
I think you'd want to have it leave a .gemspec file in the repo there so you can include it in a Gemfile for projects that want to use it from git
```
gem "scottkit", git: 'git@github.com:MikeTaylor/scottkit.git'
```
or load from a local path:
```
gem "scottkit", path: '../scottkit'
```

**Comment by MikeTaylor** [comment]
Ah, I see what's happening -- jeweler _does_ leave hehind a `scottkit.gemspec`; but because it's a generated file, I list it in the `.gitconfig` so it never gets stored in git. You think I should commit that generated file? (You are evidently much more up to date with all this ecosystem stuff than I am, so I will happily take your advice.)

**Comment by MikeTaylor** [comment]
In fact I see from https://github.com/technicalpickles/jeweler (skip down to **Releasing**) that `rake release` when using jeweler not only generates the gemspec file, it even commits it. I've been defeating that by having it in the `.gitignore`. So it certainly seems I need to not do that.

**Comment by MikeTaylor** [comment]
I think this is fixed. Please confirm.

**Comment by drewish** [comment]
Yeah that looks good

**Comment by drewish** [comment]
Oh actually good first step but looks like the file needs to be committed still.

**Comment by drewish** [comment]
Sorry was just looking at that one commit. I see the file in master now.
